# Generated by Django 2.2.2 on 2019-06-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orderinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyId', models.CharField(max_length=200)),
                ('gasId', models.CharField(max_length=200)),
                ('configId', models.CharField(max_length=200)),
                ('startCountTime', models.DateField()),
                ('isOiling', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '加油信息查询',
                'verbose_name_plural': '加油站信息',
            },
        ),
    ]
