# Generated by Django 2.2.2 on 2019-06-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returnCode', models.CharField(max_length=200, verbose_name='状态码返回')),
                ('returnMsg', models.CharField(max_length=200, verbose_name='返回消息')),
                ('data', models.CharField(max_length=200, verbose_name='返回数据')),
            ],
            options={
                'verbose_name': '接口返回信息',
                'verbose_name_plural': '接口返回信息',
            },
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='companyId',
            field=models.CharField(max_length=200, verbose_name='运营商id'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='configId',
            field=models.CharField(max_length=200, verbose_name='活动id'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='gasId',
            field=models.CharField(max_length=200, verbose_name='加油站id'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='isOiling',
            field=models.BooleanField(default=True, verbose_name='是否加油'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='startCountTime',
            field=models.DateField(verbose_name='结束时间'),
        ),
    ]
