# Generated by Django 2.2.2 on 2019-06-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptest', '0002_auto_20190619_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='credit_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pripid', models.CharField(max_length=200, verbose_name='PRIPID')),
                ('creditnum', models.CharField(max_length=200, verbose_name='统一社会信用代码')),
                ('regnum', models.CharField(max_length=200, verbose_name='注册号')),
                ('companyname', models.CharField(max_length=200, verbose_name='公司名称')),
                ('typenum', models.CharField(max_length=200, verbose_name='类型编号')),
                ('typename', models.CharField(max_length=200, verbose_name='类型名称')),
                ('liaison', models.CharField(max_length=200, verbose_name='联络员')),
                ('licardid', models.CharField(max_length=200, verbose_name='联络员证件号')),
                ('liphone', models.CharField(max_length=200, verbose_name='联络员手机号')),
            ],
            options={
                'verbose_name': '工商系统登录账号',
                'verbose_name_plural': '工商账号',
            },
        ),
    ]
