# Generated by Django 2.2.2 on 2019-07-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptest', '0003_credit_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='cbgspider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverid', models.CharField(max_length=200, verbose_name='服务器id')),
                ('name', models.CharField(max_length=200, verbose_name='用户名')),
                ('grade', models.CharField(max_length=200, verbose_name='评分')),
                ('leve', models.CharField(max_length=200, verbose_name='等级')),
                ('price', models.CharField(max_length=200, verbose_name='价格')),
                ('time_remain', models.CharField(max_length=200, verbose_name='剩余时间')),
                ('purch_url', models.CharField(max_length=200, verbose_name='购买链接')),
                ('stunn', models.CharField(max_length=200, verbose_name='绝技')),
                ('rare', models.CharField(max_length=200, verbose_name='词条')),
                ('clothes', models.CharField(max_length=200, verbose_name='衣品')),
                ('hourse', models.CharField(max_length=200, verbose_name='骏马值')),
            ],
            options={
                'verbose_name': '逆水寒账号信息',
                'verbose_name_plural': '逆水寒账号',
            },
        ),
    ]
