# Generated by Django 2.2.2 on 2019-07-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptest', '0004_cbgspider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbgspider',
            name='grade',
            field=models.IntegerField(max_length=200, verbose_name='评分'),
        ),
    ]
