# Generated by Django 2.2.2 on 2019-07-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptest', '0005_auto_20190708_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbgspider',
            name='price',
            field=models.IntegerField(max_length=200, verbose_name='价格'),
        ),
    ]
